### ISSUE TITLE
Splat dependency version out of date with requirements

### ISSUE THREAD

**Issue by rpetz** [reactiveui/ReactiveUI#928]
When fresh installing the ReactiveUI package (6.5.0) it brings in Splat 1.0.  When deriving a model from ReactiveObject it throws a compiler error stating:

Reference to type 'Splat.IEnableLogger' claims it is defined in 'Splat.dll', but it could not be found 

Upgrading Splat to the latest stable version (1.6.2) appears to resolve the issue - the nuget package dependency should be updated accordingly.

Is there a recommendation on which version should be set as the minimum for this dependency?  And if so, are there any detrimental implications to other platforms by updating it?

My environment for reproduction:
Windows 10 - Visual Studio 2015 - .Net 4.6

And another user that had the same issue (which is where I got the workaround) - looks like he's on Visual Studio 2013:
http://stackoverflow.com/questions/30963989/reactiveui-6-5-when-reactiveobject-is-inherited-in-class-i-get-a-build-error-s

**Comment by flagbug** [comment]
This was fixed with https://github.com/reactiveui/ReactiveUI/commit/a69ddf782ad0ee9d03dd879d63ac530c5b57bc64

**Comment by rpetz** [comment]
It would appear so - closing issue - thnx (sorry for not finding that commit before opening the issue)

**Comment by mattsinger** [comment]
Sorry to comment on a closed issue, but has this change been published to NuGet? I tried installing ReactiveUI this morning and the package manager still claims it relies on Splat (>= 1.0 && < 2.0).

**Comment by flagbug** [comment]
@mattsinger No it hasn't, just update Splat to the latest version manually

**Comment by aalmada** [comment]
Today I did a fresh install of reactiveui-androidsupport and I still get the same error. I had to go to Nuget and update Splat to 1.6.2.

**Comment by jbhaywood00** [comment]
I hit this too last week.  I'm totally new to RxUI and had to hit the StackOverflow just to figure out how to get it up and running because of this issue, which isn't an awesome way to start with a new framework.  Is it difficult to get the NuGet package updated so that others don't have to keep manually updating it?

**Comment by xplatsolutions** [comment]
Still an issue, installed reactiveui-core today and had to manually update Splat from 1.0.0 to 1.6.2.

**Comment by SpiegelSoft** [comment]
Still an issue

![image](https://cloud.githubusercontent.com/assets/557824/16825933/f2d19dd8-4970-11e6-89a2-dc221fbf77cd.png)

**Comment by ghuntley** [comment]
Howdy we have pushed v6.5.1 to NuGet which resolves installation into portable class libraries that target Profile259. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was causing this problem.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by JackUkleja** [comment]
I am using 7.0 and am getting this error:

> 'Could not load file or assembly 'Splat, Version=1.6.2.0,...'

Seems Splat 1.4 was installed with ReactiveUI 7.0..Having to manually installed the newer package to get this working.
